После успешного завершения posix_spawn() и posix_spawnp() помещают PID дочернего процесса в pidи возвращают 0. Если на этапе fork() возникает ошибка, дочерний элемент не создается, содержимое *pid не указано, и эти функции возвращают номер ошибки, как описано ниже.

Даже когда эти функции возвращают статус успешного завершения, дочерний процесс все равно может завершиться с ошибкой по множеству причин, связанных с его предварительнойинициализацией exec(). Кроме того, может произойти сбой. Во всех этих случаях дочерний процесс завершится со значением выхода 127.